[build]
  cmd = "go build -o ./tmp/main . && ./tmp/main -serve"
  bin = "tmp/main"
  
  include_ext = ["go", "md", "html", "css"]
  include_dir = ["content", "templates", "static"]
  
  exclude_dir = ["public", "tmp"]
  delay = 1000

[log]
  time = true